#!/usr/bin/env bash
# Configure HAproxy to send traffic to web-01 and web-02

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

frontend Hilda.Munjuri
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 542082-web-01 54.208.230.191
        server 100261-web-02 100.26.18.72

' >> /etc/haproxy/haproxy.cfg

service haproxy restart
