#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd.

while read -r line
do
    IFS=':' read -r username password uid gid gecos homedir shell <<< "$line"
    
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home directory: $homedir"
    
done < /etc/passwd
