#!/usr/bin/env bash
# A Bash script that displays the content of the current directory

for file in ./*
do
    if [ -f "$file" ]; then 
        filename=$(basename "$file")
        name_after_dash=$(echo "$filename" | cut -d'-' -f2)
        echo "$name_after_dash"
    fi
done
